### ISSUE TITLE
Tuition Payment Plans mess up Student Debt Calc

### ISSUE THREAD

**Issue by saintsoup52** [cfpb/student-debt-calculator#36]
Thanks to @higs4281 for catching this... under different tuition payment plan scenarios the student debt calculator breaks. Specifically, changing the length of the program length breaks different the "Estimated Debt @ Graduation" and "Monthly Payment" calculations. 

For example... this shouldn't be possible:
![image](https://cloud.githubusercontent.com/assets/4397508/25739185/cfb42ad4-314e-11e7-989a-10277ef53a08.png)

**Where the issue likely is hiding**
https://github.com/cfpb/student-debt-calculator/blob/master/src/loans/tuition-repayment.js

Looks like when there is an error the calculations revert back to "0". I am betting the error is being caused by the tests determining the length of the sub / unsub terms of the loans.

**Example URL***
https://www.consumerfinance.gov/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=475121&pid=5434&oid=36B1E2C6F9203DD9C4413DC84B421EEF8E736194&book=0&gib=0&gpl=0&hous=0&insi=0&insl=37764&inst=24&leng=0&mta=0&othg=0&othr=0&parl=0&pelg=0&perl=0&ppl=0&prvl=0&prvf=0&prvi=0&schg=0&stag=0&subl=0&totl=12820&tran=0&tuit=37764&unsl=0&wkst=0#info-right

Help... @mistergone

**Comment by mistergone** [comment]
I'll look into this ASAP. I should be able to track it down.

**Comment by mistergone** [comment]
Just to make sure everyone is seeing the same thing as me - the problem occurs __only__ when selecting a Program Length of less than 2 years? For instance, at 2 years and over, everything is correct. When the Program Length is set at 6 months, 1 year, or 1.5 years, then it reverts to $0 total cost of repayment and $0 monthly?

This was always the tricky part, but I think I'm on to it. Please confirm that's what you're seeing as far as errors go.

**Comment by saintsoup52** [comment]
Thank you for looking at this... I tried to suss it out but my inability to read exactly what the code was doing meant I could only diagnose so far.

So i think there are two separate issues here.
1) The total cost of repayment
2) Estimated debt when repayment begins

**Total cost of repayment**
The total cost of repayment is not including the tuition payment plan in some instances. As you noted above this seems to trigger when the length of the program is less or equal to the repayment period (which was 24 months in the URL above).

**Estimated debt when repayment begins**
The estimated debt when repayment begins is also not including tuition repayment plans but this seems to be in every instance not just the ones we notice above.This seems to be a separate calculation issue and may have been a design decision.

**Comment by mistergone** [comment]
Yeah, I was a little confused about what was happening, but you filled in the missing piece for me, @saintsoup52 

### Total cost of repayment bug
What's happening is that the `insi` (institutional loan rate) in the URL is `0`, and `student-debt-calc` was unprepared for that. When there is an unsubsidized portion to repay after `programLength`,  it doesn't check for a 0% loan, and thus the calculation comes out to a $0 monthly payment, and thus $0 . I can deploy a quick fix for this today.

### Estimated debt when repayment begins
This was somewhat due to the bug above. To be precise:
* __Case 1, The term of the Tuition Repayment Plan is less than or equal to the program length__: In this case, the student has repaid the TPR before repayment begins, so I think we decided it would be confusing if we put the TPR in the calculation of "estimated debt when repayment begins" when it would have been repaid during the program.

* __Case 2, The term of the Tuition Repayment Plan is greater than the program length__: In this case, the remaining balance of the TPR (when the program ends and repayment begins) is included in the calculation, and there will be a non-zero value for "estimated debt when repayment begins". However, the bug above is preventing that number from being calculated correctly when the `insi` (institutional loan rate) is 0.

I'll work with @higs4281 to see if he can help me get the fix into `college-costs` and onto our production servers.

**Comment by higs4281** [comment]
production shepherd at your service!
